export enum ColorEnum {
  BLACK = 'negro',
  WHITE = 'blanco',
  RED = 'rojo',
  BLUE = 'azul',
  GREEN = 'verde',
  YELLOW = 'amarillo',
  GRAY = 'gris',
  BROWN = 'marron',
  BEIGE = 'beige',
  BURGUNDY = 'bordo',
  ECRU_BLUE = 'crudo azul',
  ECRU_RED = 'crudo rojo',
  ECRU_GREEN = 'crudo verde',
  CAMOUFLAGE = 'camuflaje',
  PINK = 'rosa',
}
